#include <cstddef>
#include <cstdint>
#include <cstring>
#include <pgmspace.h>

#include "embedded_rom.h"

// Auto-generated by scripts/embed_rom.py on 2025-10-10T04:58:17.095326Z
// Entries: 0

namespace {

} // namespace

const size_t kEmbeddedRomCount = 0u;
const EmbeddedRomEntry *const kEmbeddedRoms[1] = { nullptr };

const EmbeddedRomEntry *embedded_rom_get_autoboot() {
  return nullptr;
}

const EmbeddedRomEntry *embedded_rom_get(size_t index) {
  (void)index;
  return nullptr;
}

const EmbeddedRomEntry *embedded_rom_find(const char *id) {
  if(id == nullptr) {
    return nullptr;
  }
  return nullptr;
}

