#include <cstddef>
#include <cstdint>
#include <cstring>
#include <pgmspace.h>

#include "embedded_rom.h"

#if defined(ENABLE_EMBEDDED_ROMS) && ENABLE_EMBEDDED_ROMS

// Auto-generated by scripts/embed_rom.py on 2025-10-10T13:30:55.394232Z
// Entries: 0

namespace {

} // namespace

const size_t kEmbeddedRomCount = 0u;
const EmbeddedRomEntry *const kEmbeddedRoms[1] = { nullptr };

const EmbeddedRomEntry *embedded_rom_get_autoboot() {
  return nullptr;
}

const EmbeddedRomEntry *embedded_rom_get(size_t index) {
  (void)index;
  return nullptr;
}

const EmbeddedRomEntry *embedded_rom_find(const char *id) {
  if(id == nullptr) {
    return nullptr;
  }
  return nullptr;
}

#else

const size_t kEmbeddedRomCount = 0u;
const EmbeddedRomEntry *const kEmbeddedRoms[1] = { nullptr };

const EmbeddedRomEntry *embedded_rom_get_autoboot() {
  return nullptr;
}

const EmbeddedRomEntry *embedded_rom_get(size_t index) {
  (void)index;
  return nullptr;
}

const EmbeddedRomEntry *embedded_rom_find(const char *id) {
  (void)id;
  return nullptr;
}

#endif // ENABLE_EMBEDDED_ROMS

